version: '3.3'
services:
  app_feegow:
    container_name: app_feegow
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend/:/var/www
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1
    networks:
      - laravel

  mysql_feegow:
    image: mysql:8.0
    container_name: mysql_feegow
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeevax
      MYSQL_USER: feegow
      MYSQL_PASSWORD: 987654321
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/ 
    networks:
      - laravel

  node:
    image: node:18
    container_name: node
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run serve
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge